version: '3'

services:
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    depends_on:
        - flask-app
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

#  flask-app:
#    build: .
#    container_name: flask-app
#    ports:
#      - 5000:5000
#    restart: on-failure

  flask-app:
    build: .
    ports:
      - 5000:5000
    restart: always
    volumes:
      - flask-data:/usr/src/app
volumes:
  flask-data: {}
