---
- name: Fetch the repo from GitHub
  git:
    repo: 'https://github.com/RupGautam/py-flask-ansible-docker.git'
    clone: yes
    dest: ./flask-app

- name: Activate venv for python
  pip:
    requirements: ./flask-app/requirements.txt
    virtualenv: ./flask-app/env
    virtualenv_python: python3.7


- name: Create services
  docker_compose:
    project_src: ./flask-app
    